### ISSUE TITLE
language select should redirect to same page

### ISSUE THREAD

**Issue by Shekharrajak** [Shekharrajak/scipy-sphinx-theme-v2#34]
Navbar have dropdown option to select the language but it redirects to the main landing page. So we want to redirect it to same page which is opened that time.

i.e. If user is at about page then selecting the language: dutch should be redirected to the about page only with the translated page (`nl/about.html`) and all other links in that page should be changed with `nl/page_name.html`.

**Comment by rgommers** [comment]
I'm still not sure that this is going in the right direction. We want translations to integrate with Hugo, not with Sphinx. So I'd suggest to not mix the Sphinx theming and translations. 

Perhaps if the website translations are successful and popular, we will want to translate some beginner tutorials. But that's for much later to decide.

**Comment by Shekharrajak** [comment]
Ah! Thanks for letting me know this. I should do changes in newsite branch of the numpy.org repo.

**Comment by rgommers** [comment]
Yes indeed:)
