### ISSUE TITLE
Left menu has numbered entries

### ISSUE THREAD

**Issue by mattip** [Shekharrajak/scipy-sphinx-theme-v2#41]
Looking at the latest pr https://pr-29-scipy-sphinx-theme-v2.surge.sh/, the left side menu is numbered. Is that on purpose?

**Comment by Shekharrajak** [comment]
In this repo I am directly using the old demo doc code which is present [here](https://github.com/scipy/scipy-sphinx-theme/blob/master/index.rst) and as per the rst file it is numbered so it is coming ( [see file index.rst](https://github.com/Shekharrajak/scipy-sphinx-theme-v2/blob/master/demo-docs/index.rst) ).

You can verify it in newly generated devdoc using this theme:  http://generated-numpy-docs-14648-sphinx2.surge.sh/ and http://generated-numpy-neps-sphinx2.surge.sh/

**Comment by mattip** [comment]
Thanks for letting me know. The new theme looks quite nice
